name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update && sudo apt -y install luarocks lua5.1 && sudo luarocks install luacheck
      - uses: actions/checkout@v1
      - name: Lint mta resources
        run: |
          luacheck --exclude-files '**/dp_class.lua' ./
